site_name: Siddhi-IO-JMS
extra_css:
- stylesheets/extra.css
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi IO JMS: index.md
- License: license.md
- Api:
  - 1.0.4-SNAPSHOT: api/1.0.4-SNAPSHOT.md
  - 1.0.5-SNAPSHOT: api/1.0.5-SNAPSHOT.md
theme: material
